### ISSUE TITLE
Weird interaction with phasing in PlayerBattle

### ISSUE THREAD

**Issue by rnoriega31** [rnoriega31/TBARPG#13]
If while phasing the player presses dash, the phasing is canceled but the dash isn't executed. And once the phasing button is released then the animation for un-phasing plays even though phasing was canceled previously.

**Comment by ericdsw** [comment]
Another issue related with phasing: when energy runs out, player is no longer phasing but animation is still playing.

**Comment by ericdsw** [comment]
When energy is depleted, `PhaseAction` will call the `finish()` method on every `_fixed_process` tick, which causes the weird behavior described above. Possible solution: force a cooldown of X amount of seconds so that the player visibly changes to the "default" state.
