### ISSUE TITLE
Add a 'Hitstun' state to player.

### ISSUE THREAD

**Issue by rnoriega31** [rnoriega31/TBARPG#17]
Currently, through the implementation of animations for `PlayerBattle`, the player is not able to move (and consequently dash or roll) out of hitstun but it would be better to add a hitstun state that would additionally prevent the player from attacking, shooting, and phasing before the hitstun ends, things that are able to be done as of the making of this issue.

**Comment by ericdsw** [comment]
This state should have the following behavior:
- It's duration should be the same as the `"got_hit"` animation
- Overrides any previous state
- Should block ability to dash, roll and phase (become ethereal) while it's active
- Should always return to STATE_IDLE
