### ISSUE TITLE
Implement dynamic enemies on the battle

### ISSUE THREAD

**Issue by ericdsw** [rnoriega31/TBARPG#2]
For now, the enemy is hardcoded. there should be a component that decides what enemy needs to be spawn.

**Comment by rnoriega31** [comment]
This might be unnecessary since there are no random encounters and all fights are set encounters. Could be managed by simply instancing the correct boss in-editor.

**Comment by ericdsw** [comment]
Can consider: StartBattleCutsceneEvent

**Comment by ericdsw** [comment]
Enemies are now provided via a custom `CutsceneEvent` called `BattleEvent`.
