### ISSUE TITLE
Camera bouncing during battle.

### ISSUE THREAD

**Issue by rnoriega31** [rnoriega31/TBARPG#36]
If the player is at a certain Y-distance from the enemy during battle, moving horizontally or even attacking will cause the screen to "bounce" in the Y-axis even though no vertical movement is being made.

**Comment by rnoriega31** [comment]
Does not happen when using a dodge roll.

**Comment by ericdsw** [comment]
Problem was when calculating priority_target_rect, as the sprite size was being used and different move animations have different sprite sizes. Now is a static 64x64 square.
