### ISSUE TITLE
Finish minor settings implementation

### ISSUE THREAD

**Issue by ericdsw** [rnoriega31/TBARPG#55]
- [x] Aim mode is not being applied.
- [ ] ~~Vibration is being ignored for controllers.~~ (tbd: when the controller should vibrate, or if it should vibrate at all.
- [x] Input remapping needs a call to action (like: "Press any key")
- [x] Input remapping needs a "Restore Default" option.
- [x] Pause's main menu needs an option to "Return to the Game"
- [x] Pressing back on the pause's main menu screen should close the pause screen.

**Comment by rnoriega31** [comment]
- [ ] The interact button is not being used for interacting (talking to NPCs, advancing through dialogue, menu-ing).
- [ ] You can map the same key to two functionalities, this should not happen.
- [ ] If `J` and `K` will always work as `accept` and `back` in the menu, that information should be displayed somehow. Either as greyed out options in the input mapping or as command prompt in a corner.
- [ ] Allow players using a controller to move with the D-pad.

**Comment by ericdsw** [comment]
Setting a key binding that already exists for another action will swap the keys between them.

**Comment by ericdsw** [comment]
- [ ] Add small timeout before pause screens can listen to the player's input. This prevents actions leaking from one screen to another when navigating.
